# NumPy Arrays - Part 4<br>

by uramoon@kw.ac.kr<br>
원본 출처: Introduction to Deep Learning at Carnegie Mellon University (https://deeplearning.cs.cmu.edu/S22/index.html)

In [1]:
# Import the NumPy 
import numpy as np

## Reshaping Arrays (배열의 모양을 다르게 해석하기)<br>

Array reshaping은 배열안의 데이터는 그대로 두고 모양을 바꿔 해석을 다르게 하는 것입니다.

예를 들어 (4,) 모양의 1차원 배열 [1, 2, 3, 4]는 (4, 1) 모양의 2차원 배열 [[1], [2], [3], [4]], <br> 또는 (2, 2) 모양의 2차원 배열 [[1, 2], [3, 4]] 및 (1, 4) 모양의 2차원 배열 [[1, 2, 3, 4]]로 형태를 바꿔 해석할 수도 있습니다.

### 동일 차원으로 reshaping

In [2]:
s = np.random.rand(3, 4, 5)
print(f"원래 모양: {s.shape}")

원래 모양: (3, 4, 5)


***TODO: s의 전체 원소 개수 구하기***
* Q: 어떻게 계산할 수 있을까요?
* A: (3 * 4 * 5= 60)

In [3]:
s.size

60

In [4]:
# s 내용 확인하기
print(s)

[[[0.65392478 0.21712082 0.73588349 0.86088565 0.11052408]
  [0.50936276 0.69658208 0.91920565 0.48327638 0.6130248 ]
  [0.28110062 0.16777829 0.06903175 0.58300481 0.06758554]
  [0.17259058 0.83022629 0.87411216 0.75884227 0.2784306 ]]

 [[0.83531438 0.45353227 0.14845481 0.12499071 0.69739524]
  [0.81110422 0.9984923  0.09830826 0.81730964 0.56906697]
  [0.3043856  0.50831238 0.58767243 0.64916253 0.4618935 ]
  [0.75723091 0.51807737 0.38306646 0.52943058 0.22265236]]

 [[0.94717995 0.63406934 0.73680865 0.7897106  0.29339432]
  [0.74333256 0.95294144 0.99249195 0.76572217 0.85861329]
  [0.4380713  0.68700809 0.75733375 0.93577598 0.92624861]
  [0.71829943 0.1934346  0.6841501  0.37107827 0.67447842]]]


In [5]:
# TODO: s를 (2, 6, 5)로 reshape하여 s1에 저장하기
s1 = s.reshape(2, 6, 5)
print(f"s1의 모양: {s1.shape}")

s1의 모양: (2, 6, 5)


In [6]:
# s와 s1의 각 원소값과 위치는 동일한 것을 확인해보세요.
print(s1)

[[[0.65392478 0.21712082 0.73588349 0.86088565 0.11052408]
  [0.50936276 0.69658208 0.91920565 0.48327638 0.6130248 ]
  [0.28110062 0.16777829 0.06903175 0.58300481 0.06758554]
  [0.17259058 0.83022629 0.87411216 0.75884227 0.2784306 ]
  [0.83531438 0.45353227 0.14845481 0.12499071 0.69739524]
  [0.81110422 0.9984923  0.09830826 0.81730964 0.56906697]]

 [[0.3043856  0.50831238 0.58767243 0.64916253 0.4618935 ]
  [0.75723091 0.51807737 0.38306646 0.52943058 0.22265236]
  [0.94717995 0.63406934 0.73680865 0.7897106  0.29339432]
  [0.74333256 0.95294144 0.99249195 0.76572217 0.85861329]
  [0.4380713  0.68700809 0.75733375 0.93577598 0.92624861]
  [0.71829943 0.1934346  0.6841501  0.37107827 0.67447842]]]


### 다른 차원으로 reshaping

In [10]:
# TODO: 0부터 119까지 120개의 정수로 이루어진 1차원 배열을 간단하게 만들어보세요.
r = np.arange(120)

In [11]:
print(f"원래 모양: {r.shape}")

원래 모양: (120,)


In [13]:
# TODO: (120,) -> (3, 4, 10)
# 원소개수는 120개로 동일합니다.
r1 = r.reshape(3,4,10)
print(f"r1의 모양: {r1.shape}")

r1의 모양: (3, 4, 10)


In [14]:
# r과 r1을 비교해보세요.
print(r)
print(r1)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]
[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]]

 [[ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]]

 [[ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]
  [100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 1

In [15]:
# TODO: r1을 reshape하여 r2에 저장하세요.
# (3, 4, 10) -> (6, 20)
r2 = r1.reshape(6,20)
print(f"r2의 모양: {r2.shape}")

r2의 모양: (6, 20)


In [16]:
# r2와 r1, r을 비교해보세요.
print(r1)
print(r2)

[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]]

 [[ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]]

 [[ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]
  [100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]]]
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]
 [100 101 102 103 104 105 106 107 108 109

## 배열 펼치기 (Flattening)
배열 펼치기는 다차원 배열을 일차원으로 만들어줍니다.<br>
일반적인 다층 퍼셉트론 인공 신경망은 일차원 배열을 입력으로 받기 때문에<br> MNIST 데이터셋을 사용하면 28 x 28 2차원 배열을 길이 784의 일차원 배열로 만들어 사용합니다.

In [17]:
k = np.random.rand(5, 6)
k

array([[0.64640465, 0.21461514, 0.80959157, 0.83936112, 0.47375952,
        0.35758676],
       [0.64179528, 0.99535088, 0.92456001, 0.00539442, 0.6304778 ,
        0.43785407],
       [0.43756692, 0.90245854, 0.85640323, 0.33679057, 0.47508738,
        0.08867289],
       [0.15127567, 0.92105475, 0.46462124, 0.12967916, 0.55272392,
        0.28080413],
       [0.51846883, 0.94507563, 0.51111159, 0.55183713, 0.47492139,
        0.94739144]])

### 기본 순서대로 펼치기

In [18]:
# k와 k1을 비교해보세요.
k1 = k.flatten() 
k1

array([0.64640465, 0.21461514, 0.80959157, 0.83936112, 0.47375952,
       0.35758676, 0.64179528, 0.99535088, 0.92456001, 0.00539442,
       0.6304778 , 0.43785407, 0.43756692, 0.90245854, 0.85640323,
       0.33679057, 0.47508738, 0.08867289, 0.15127567, 0.92105475,
       0.46462124, 0.12967916, 0.55272392, 0.28080413, 0.51846883,
       0.94507563, 0.51111159, 0.55183713, 0.47492139, 0.94739144])

In [19]:
k1.shape

(30,)

## 배열 이어 붙이기
https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [20]:
# 2차원 배열인 array1과 array2 생성
array1 = np.array([[1, 2], [3, 4]])
print("Array 1 is \n", array1, " with dimensions ", array1.shape, "\n")

array2 = np.array([[5, 6]])
print("Array 2 is \n", array2, " with dimensions ", array2.shape, "\n")

Array 1 is 
 [[1 2]
 [3 4]]  with dimensions  (2, 2) 

Array 2 is 
 [[5 6]]  with dimensions  (1, 2) 



배열을 이어붙일 때에는 기준이 되는 축 이외에 모양이 동일해야 합니다.<br>
1. (2, 2)와 (1, 2) 이어 붙일 때 0번 인덱스로 이어붙이면 (3, 2) 배열 탄생
2. (2, 2)와 (1, 2) 이어 붙일 때 1번 인덱스로 이어붙이면 0번 인덱스의 모양이 서로 다르므로 이어붙이기 실패

In [23]:
# TODO: 0번 인덱스를 기준으로 array1과 array2를 이어붙이세요.
concatenated_array1 = np.concatenate((array1, array2), axis =0)
print("Concatenated array 1 along axis 0 (row-wise for 2-d arrays) is \n", concatenated_array1, "with dimensions ", concatenated_array1.shape, '\n')

Concatenated array 1 along axis 0 (row-wise for 2-d arrays) is 
 [[1 2]
 [3 4]
 [5 6]] with dimensions  (3, 2) 



In [25]:
# TODO: 1번 인덱스를 기준으로 array1과 array2를 이어붙이세요. (실패합니다. 에러 메시지를 확인하세요.)
concatenated_array2 = np.concatenate((array1, array2), axis = 1)
print("Concatenated array 2 along axis 0 (column-wise for 2-d arrays) is \n", concatenated_array2, "with dimensions ", concatenated_array2.shape)

ValueError: ignored

In [26]:
# TODO: (3, 4, 5) 형태에 3 미만의 무작위 정수로 채워진 배열을 만드세요.
# https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html
array1 = np.random.randint(3,size = (3,4,5))
print("Array 1 is \n", array1, " with dimensions ", array1.shape, "\n")

Array 1 is 
 [[[0 1 0 0 1]
  [2 0 1 0 1]
  [1 0 2 2 0]
  [2 1 1 1 0]]

 [[0 0 1 1 0]
  [1 1 2 1 0]
  [1 2 1 1 0]
  [2 1 2 1 2]]

 [[0 1 1 0 0]
  [1 0 2 0 0]
  [2 0 1 0 1]
  [0 2 1 2 2]]]  with dimensions  (3, 4, 5) 



In [27]:
# TODO: (3, 4, 5) 형태에 4 미만의 무작위 정수로 채워진 배열을 만드세요.
array2 = np.random.randint(4, size = (3,4,5))
print("Array 2 is \n", array2, " with dimensions ", array2.shape, "\n")

Array 2 is 
 [[[2 2 0 3 0]
  [1 0 2 3 1]
  [1 0 0 3 0]
  [2 0 1 1 3]]

 [[3 3 1 0 1]
  [0 2 1 1 3]
  [3 2 0 1 3]
  [1 3 2 0 2]]

 [[0 3 3 3 2]
  [1 3 1 1 3]
  [2 3 2 2 1]
  [0 2 2 2 0]]]  with dimensions  (3, 4, 5) 



***TODO: 0번 인덱스를 기준으로 이어붙이기***
* Q: 어떤 모양일까요? (코딩으로 결과 확인 전에 작성해보세요.)
* A: (4,5) 배열이 6묶음인 형태일 것 같다.

In [28]:
# TODO: 0번 인덱스를 기준으로 이어붙이기
concatenated_array1 = np.concatenate((array1, array2), 0)
print("Concatenated array 1 is \n", concatenated_array1, "\n\n", "and the dimensions of the concatenated array 1 are: \n", concatenated_array1.shape)

Concatenated array 1 is 
 [[[0 1 0 0 1]
  [2 0 1 0 1]
  [1 0 2 2 0]
  [2 1 1 1 0]]

 [[0 0 1 1 0]
  [1 1 2 1 0]
  [1 2 1 1 0]
  [2 1 2 1 2]]

 [[0 1 1 0 0]
  [1 0 2 0 0]
  [2 0 1 0 1]
  [0 2 1 2 2]]

 [[2 2 0 3 0]
  [1 0 2 3 1]
  [1 0 0 3 0]
  [2 0 1 1 3]]

 [[3 3 1 0 1]
  [0 2 1 1 3]
  [3 2 0 1 3]
  [1 3 2 0 2]]

 [[0 3 3 3 2]
  [1 3 1 1 3]
  [2 3 2 2 1]
  [0 2 2 2 0]]] 

 and the dimensions of the concatenated array 1 are: 
 (6, 4, 5)


***TODO: 1번 인덱스를 기준으로 이어붙이기***
* Q: 어떤 모양일까요? (코딩으로 결과 확인 전에 작성해보세요.)
* A: 3개의 묶음에서 행이 늘어난 형태일 것 같다.

In [29]:
# TODO: 1번 인덱스를 기준으로 이어붙이기
concatenated_array2 = np.concatenate((array1, array2), 1)
print("Concatenated array 2 is \n", concatenated_array2, "\n\n", "and the dimensions of the concatenated array 2 are: \n", concatenated_array2.shape)

Concatenated array 2 is 
 [[[0 1 0 0 1]
  [2 0 1 0 1]
  [1 0 2 2 0]
  [2 1 1 1 0]
  [2 2 0 3 0]
  [1 0 2 3 1]
  [1 0 0 3 0]
  [2 0 1 1 3]]

 [[0 0 1 1 0]
  [1 1 2 1 0]
  [1 2 1 1 0]
  [2 1 2 1 2]
  [3 3 1 0 1]
  [0 2 1 1 3]
  [3 2 0 1 3]
  [1 3 2 0 2]]

 [[0 1 1 0 0]
  [1 0 2 0 0]
  [2 0 1 0 1]
  [0 2 1 2 2]
  [0 3 3 3 2]
  [1 3 1 1 3]
  [2 3 2 2 1]
  [0 2 2 2 0]]] 

 and the dimensions of the concatenated array 2 are: 
 (3, 8, 5)


***TODO: 2번 인덱스를 기준으로 이어붙이기***
* Q: 어떤 모양일까요? (코딩으로 결과 확인 전에 작성해보세요.)
* A: 각 묶음에서 열이 늘어난 형태일 것 같다.

In [30]:
# TODO: 2번 인덱스를 기준으로 이어붙이기
concatenated_array3 = np.concatenate((array1, array2), 2)
print("Concatenated array 3 is \n", concatenated_array3, "\n\n", "and the dimensions of the concatenated array 3 are: \n", concatenated_array3.shape)

Concatenated array 3 is 
 [[[0 1 0 0 1 2 2 0 3 0]
  [2 0 1 0 1 1 0 2 3 1]
  [1 0 2 2 0 1 0 0 3 0]
  [2 1 1 1 0 2 0 1 1 3]]

 [[0 0 1 1 0 3 3 1 0 1]
  [1 1 2 1 0 0 2 1 1 3]
  [1 2 1 1 0 3 2 0 1 3]
  [2 1 2 1 2 1 3 2 0 2]]

 [[0 1 1 0 0 0 3 3 3 2]
  [1 0 2 0 0 1 3 1 1 3]
  [2 0 1 0 1 2 3 2 2 1]
  [0 2 1 2 2 0 2 2 2 0]]] 

 and the dimensions of the concatenated array 3 are: 
 (3, 4, 10)
