# NumPy Arrays - Part 3<br>
NumPy - 대규모의 다차원 배열을 쉽게 처리할 때 사용하는 파이썬 라이브러리<br>

원본 출처: Introduction to Deep Learning at Carnegie Mellon University (https://deeplearning.cs.cmu.edu/S22/index.html)

In [1]:
# Import the NumPy 
import numpy as np

## 1. 데이터 읽어오기

### a. 인덱싱: NumPy 배열에서 값 읽어오기

In [2]:
# TODO: 무작위 값으로 채워진 4 x 5 x 6 배열을 만들어보세요. (5 x 6 행렬이 4개 묶음 있는 것으로 해석할 수 있음)
n = np.random.rand(4, 5, 6)
n.shape

(4, 5, 6)

나중에 다룰 MNIST (필기체 인식) 데이터셋의 모양은 (60000, 28, 28)인데
28 (행의 수, 높이) x 28 (열의 수, 너비)의 그림 60000만장이 있는 것으로 해석됩니다.

In [3]:
# TODO: n에서 두 번째 묶음의 세 번째 행, 네 번째 열의 값은? (인덱스는 0에서 시작함)

n[1][2][3]

0.651946069846237

### b. 슬라이싱: NumPy 배열의 일부를 가져오기

시작(포함):끝(미포함)으로 연속된 항목을 슬라이싱 <br>
:만 쓰면 전체

In [4]:
# 첫 번째 묶음의 모든 행렬 가져오기
print(n[0, :, :]) # same as: n[0], 정답이므로 수정할 필요 없음

[[0.37961403 0.35343582 0.18431072 0.91449883 0.02803589 0.65904709]
 [0.31086334 0.8942623  0.70057089 0.94234077 0.93477234 0.77186048]
 [0.17019914 0.43063838 0.62551194 0.40197565 0.63986615 0.69801393]
 [0.44553565 0.29985994 0.83327442 0.79536693 0.77079176 0.16533487]
 [0.45013649 0.2751294  0.34306423 0.43522541 0.84796643 0.86028351]]


In [5]:
# TODO: 첫 번째 묶음에서 [0, 3) 행, [0, 4) 열 가져오기, 즉 3 x 4 배열이 나와야 함
print(n[0,0:3,0:4])

[[0.37961403 0.35343582 0.18431072 0.91449883]
 [0.31086334 0.8942623  0.70057089 0.94234077]
 [0.17019914 0.43063838 0.62551194 0.40197565]]


In [6]:
# TODO: 전체 묶음에서 4번 째 행, 5번째 열 값들 가져오기
print(n[:,3 ,4 ]) 

[0.77079176 0.9634853  0.6167636  0.97377801]


### c. Slicing at Interval
시작::증가폭(스텝)으로 띄엄띄엄 슬라이싱<br>
예) a[7::2]인 경우 a[7], a[9], a[11], ... 을 가져와서 배열로 만듦

In [7]:
# TODO: 0번 묶음, 2번 묶음, 4번 묶음, ... 슬라이싱 (n은 3번 묶음까지만 있어서 두 개의 묶음만 출력됨)
print(n[0::2]) 

[[[0.37961403 0.35343582 0.18431072 0.91449883 0.02803589 0.65904709]
  [0.31086334 0.8942623  0.70057089 0.94234077 0.93477234 0.77186048]
  [0.17019914 0.43063838 0.62551194 0.40197565 0.63986615 0.69801393]
  [0.44553565 0.29985994 0.83327442 0.79536693 0.77079176 0.16533487]
  [0.45013649 0.2751294  0.34306423 0.43522541 0.84796643 0.86028351]]

 [[0.78988638 0.6725412  0.07289771 0.9558491  0.2961084  0.26667978]
  [0.49153406 0.38544842 0.7943033  0.73479234 0.21160078 0.57107296]
  [0.27437412 0.38436003 0.95440233 0.4035846  0.54286219 0.02259375]
  [0.49827203 0.16159007 0.10387547 0.39826394 0.6167636  0.84939246]
  [0.56522046 0.23389181 0.49685155 0.56585447 0.96297473 0.93662906]]]


원래 n의 모습과 비교해가며 아래의 결과는 어떻게 만들어진 것인지 이해하고 넘어가세요.

In [8]:
print(n[0::2, 1:4, 1::2]) 

[[[0.8942623  0.94234077 0.77186048]
  [0.43063838 0.40197565 0.69801393]
  [0.29985994 0.79536693 0.16533487]]

 [[0.38544842 0.73479234 0.57107296]
  [0.38436003 0.4035846  0.02259375]
  [0.16159007 0.39826394 0.84939246]]]


## 2. 데이터 수정하기

In [9]:
# 배열 복사하기
n_copy = np.copy(n)

### a. 하나의 값 수정하기

In [10]:
# 복사한 배열과 n이 같은지 하나의 항목 확인
print(n_copy[2, 4, 1] == n[2, 4, 1])

True


In [11]:
# TODO: 복사한 배열 n_copy[2, 4, 1]의 값을 0.005로 변경
n_copy[2,4,1]=0.005

# 여전히 내용이 같은지 확인
print(n_copy[2, 4, 1] == n[2, 4, 1])

False


n_copy는 n을 복사한 것이지만 n과 다른 위치에 독립적으로 존재한다. 만약 copy 함수로 복사하지 않고 m = n으로 m을 만든다음 m[2, 4, 1] 값을 수정하면 어떻게 될까? 

In [12]:
print('Before: ', n[2, 4, 1])
m = n
m[2, 4, 1] = 0.5
print('After: ', n[2, 4, 1])

Before:  0.23389180700681
After:  0.5


In [13]:
# n, m, n_copy가 저장된 장소 출력
print(id(n))
print(id(m))
print(id(n_copy))

140050662059536
140050662059536
140050634332176


### b. 여러 항목의 값을 같은 값으로 수정하기

In [14]:
n_copy = np.copy(n)

# n_copy 3번째 묶음의 4번째 행의 값 확인
print(n_copy[2, 3])

[0.49827203 0.16159007 0.10387547 0.39826394 0.6167636  0.84939246]


In [15]:
# TODO: n_copy 3번째 묶음, 4번째 행의 값을 모두 0.5로 바꾸기
n_copy[2, 3] = 0.5

# n_copy 3번째 묶음의 4번째 열의 값 확인
print(n_copy[2, 3])

[0.5 0.5 0.5 0.5 0.5 0.5]
